### PR TITLE
Update and add deploy script

### PR DESCRIPTION
**Pull request by eggplants**
I added `deploy.sh` that can build various versions of images with tags and push them to DockerHub, and a corresponding Dockerfile.

Egison 0.x - 3.8.x is not able to build on haskell:7 - haskell:9

- [x] Egison 3.x
  - 3.9.3 3.9.4 3.10.0 3.10.1 3.10.2 3.10.3
- [x] Egison 4.x
  - 4.0.0 4.0.1 4.0.2 4.0.3 4.1.0 4.1.1 4.1.2

My repo (test):
https://hub.docker.com/r/eggplanter/egison/tags?page=1&ordering=name

### CODE REVIEW

**Comment by eggplants** [comment]
To enable CI to push to DockerHub, please set `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` to secrets.

**Comment by eggplants** [comment]
@egisatoshi

**Comment by egisatoshi** [comment]
Thank you very much!

**Comment by eggplants** [comment]
You can run deploying CI manually.
Try it after set secrets.

Ref: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

If you find it annoying that Deploy CI runs on push triggers, please delete the following part.

https://github.com/egison/docker-egison/blob/f06fda989d33784af543efa4a15dce254f87000f/.github/workflows/deploy.yml#L3-L5

**Comment by egisatoshi** [comment]
Thank you for the link!
I'll try ASAP, tomorrow if possible!!

**Comment by egisatoshi** [comment]
@eggplants 

Screen Shot 2021-12-12 at 15 09 37

I set `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` to secrets and run jobs from the "Actions" tab on the GitHub repository page.
But we've got the above error. Do you know the reason for the error?

**Comment by egisatoshi** [comment]
@eggplants Thank you very much! We've succeeded in deploying the latest Egison.

**Pull request merged**
