### PR TITLE
Remove extra `break`

### PR DESCRIPTION
**Pull request by eggplants**

### CODE REVIEW

**Comment by egisatoshi** [comment]
Thank you!

**Comment by eggplants** [comment]
I'm sorry for my mistake...

**Comment by eggplants** [comment]
💯
Screenshot_2021-12-12-17-11-16-46_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by egisatoshi** [comment]
@eggplants 
No problem at all. Thank you for your contributions!

**Pull request merged**
